In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [2]:
produk_df = pd.read_csv('dataset/amazon_product_cleaned.csv')
produk_df.head(10)

,index,name,main_category,sub_category,ratings,no_of_ratings,discount_price_idr,actual_price_idr,stock
0,1,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,2255,6134184,10965651,50
1,2,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,2948,8642026,14125781,62
2,3,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,1206,6411346,11523321,448
3,4,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,7061961,12824551,478
4,5,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,6411346,12601483,344
5,6,Voltas 1.4 Ton 3 Star Inverter Split AC(Copper...,appliances,Air Conditioners,4.0,1666,5946621,13196331,148
6,7,Lloyd 1.0 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,1097,5576514,9292641,423
7,8,Lloyd 1.5 Ton 5 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.3,1494,7433741,12638661,316
8,9,Carrier 1 Ton 3 Star AI Flexicool Inverter Spl...,appliances,Air Conditioners,4.1,674,5760731,10816939,250
9,10,"Voltas 1.5 Ton, 5 Star, Inverter Split AC(Copp...",appliances,Air Conditioners,4.0,801,7063634,13754001,298

In [3]:
start_date = datetime.strptime("2025-04-01", "%Y-%m-%d")
end_date = datetime.strptime("2025-04-15", "%Y-%m-%d")

In [4]:
delta_hari = (end_date - start_date).days + 1

In [6]:
for i in range(delta_hari):
    current_date = start_date + timedelta(days=i)
    daily_sales = produk_df[['index', 'name']].copy()
    daily_sales['date'] = current_date.strftime('%Y-%m-%d')
    
    # generate random sales data 
    daily_sales['quantity_sold'] = np.random.randint(1, 50, size=len(daily_sales))
    
    filename = f'daily_sales/daily_sales_{current_date.strftime("%Y%m%d")}.csv'
    daily_sales.to_csv(filename, index=False)
    
    print(f"File {filename} created with {len(daily_sales)} records.")

File daily_sales/daily_sales_20250401.csv created with 384827 records.
File daily_sales/daily_sales_20250402.csv created with 384827 records.
File daily_sales/daily_sales_20250403.csv created with 384827 records.
File daily_sales/daily_sales_20250404.csv created with 384827 records.
File daily_sales/daily_sales_20250405.csv created with 384827 records.
File daily_sales/daily_sales_20250406.csv created with 384827 records.
File daily_sales/daily_sales_20250407.csv created with 384827 records.
File daily_sales/daily_sales_20250408.csv created with 384827 records.
File daily_sales/daily_sales_20250409.csv created with 384827 records.
File daily_sales/daily_sales_20250410.csv created with 384827 records.
File daily_sales/daily_sales_20250411.csv created with 384827 records.
File daily_sales/daily_sales_20250412.csv created with 384827 records.
File daily_sales/daily_sales_20250413.csv created with 384827 records.
File daily_sales/daily_sales_20250414.csv created with 384827 records.
File daily_sales/daily_sales_20250415.csv created with 384827 records.

In [7]:
sales_data_1 = pd.read_csv('daily_sales/daily_sales_20250401.csv')

In [8]:
sales_data_1.head(10)

,index,name,date,quantity_sold
0,1,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,2025-04-01,22
1,2,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,2025-04-01,1
2,3,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,2025-04-01,36
3,4,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,2025-04-01,42
4,5,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,2025-04-01,17
5,6,Voltas 1.4 Ton 3 Star Inverter Split AC(Copper...,2025-04-01,48
6,7,Lloyd 1.0 Ton 3 Star Inverter Split Ac (5 In 1...,2025-04-01,33
7,8,Lloyd 1.5 Ton 5 Star Inverter Split Ac (5 In 1...,2025-04-01,45
8,9,Carrier 1 Ton 3 Star AI Flexicool Inverter Spl...,2025-04-01,20
9,10,"Voltas 1.5 Ton, 5 Star, Inverter Split AC(Copp...",2025-04-01,7